#!/bin/bash -l
#SBATCH -o ./logs/%A_%a.out
#SBATCH -e ./logs/%A_%a.err
#SBATCH --job-name=train_metalearner_functionlearning
#SBATCH --time=24:00:00
#SBATCH --constraint="gpu"
#SBATCH --gres=gpu:a100:1
#SBATCH --mem=40G
#SBATCH --cpus-per-task=18
#SBATCH --mail-type=ALL
#SBATCH --mail-user=akshaykjagadish@gmail.com

cd ~/ermi/
module purge
module load anaconda/3/2023.03
module load gcc/13 impi/2021.9
module load cuda/12.1
module load pytorch/gpu-cuda-12.1/2.2.0
pip3 install --user ipdb torch transformers tensorboard ipdb tqdm schedulefree


# BMI
# python mi/train_functionlearning.py --env-name synthetic_dim1_maxsteps25 --synthetic --num-episodes 1000000 --ess ${SLURM_ARRAY_TASK_ID} --optimizer schedulefree --offset 0 --scale 0.25 --job-array --ess-init 0.0 --annealing-fraction 0.167 --max-steps 25 --num-dims 1 --loss nll --save-dir /u/ajagadish/ermi/functionlearning/trained_models/ --save-every 100 --print-every 10  --first-run-id 0 --noise 0.01 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle 
# python mi/train_functionlearning.py --env-name synthetic_dim1_maxsteps25 --synthetic --num-episodes 500000 --ess ${SLURM_ARRAY_TASK_ID} --optimizer schedulefree --offset 0 --scale 0.25 --job-array --ess-init 0.0 --annealing-fraction 0.167 --max-steps 25 --num-dims 1 --loss nll --save-dir /u/ajagadish/ermi/functionlearning/trained_models/ --save-every 100 --print-every 10  --first-run-id 0 --noise 0.01 --model-name transformer --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle  
# python mi/train_functionlearning.py --env-name synthetic_dim1_maxsteps25 --synthetic --num-episodes 250000 --ess ${SLURM_ARRAY_TASK_ID} --optimizer adam --offset 0 --scale 0.25 --job-array --ess-init 0.0 --annealing-fraction 0.167 --max-steps 25 --num-dims 1 --loss nll --save-dir /u/ajagadish/ermi/functionlearning/trained_models/ --save-every 100 --print-every 10  --first-run-id 0 --noise 0.01 --model-name transformer --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle  
# python mi/train_functionlearning.py --env-name synthetic_dim1_maxsteps25 --synthetic --num-episodes 250000 --ess ${SLURM_ARRAY_TASK_ID} --optimizer schedulefree --offset 0 --scale 0.5 --job-array --ess-init 0.0 --annealing-fraction 0.167 --max-steps 25 --num-dims 1 --loss nll --save-dir /u/ajagadish/ermi/functionlearning/trained_models/ --save-every 100 --print-every 10  --first-run-id 0 --noise 0.01 --model-name transformer --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle  
# python mi/train_functionlearning.py --env-name synthetic_dim1_maxsteps25 --dynamic-scaling --synthetic --num-episodes 250000 --ess ${SLURM_ARRAY_TASK_ID} --optimizer schedulefree --offset 0 --scale 0.5 --job-array --ess-init 0.0 --annealing-fraction 0.167 --max-steps 25 --num-dims 1 --loss nll --save-dir /u/ajagadish/ermi/functionlearning/trained_models/ --save-every 100 --print-every 10  --first-run-id 0 --noise 0.01 --model-name transformer --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle  

# BERMI
# python mi/train_functionlearning.py --env-type claude_dim1_maxsteps25  --num-episodes 1000000 --ess ${SLURM_ARRAY_TASK_ID} --optimizer schedulefree --offset 0 --scale 0.25 --job-array --ess-init 0.0 --annealing-fraction 0.167 --max-steps 25 --num-dims 1 --sample-to-match-max-steps --loss nll --env-name claude_generated_functionlearningtasks_paramsNA_dim1_data20_tasks9991_run0_procid0_pversion2 --env-dir /u/ajagadish/ermi/functionlearning/data/generated_tasks --save-dir /u/ajagadish/ermi/functionlearning/trained_models/ --save-every 100 --print-every 10  --first-run-id 0 --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle 
# (replicate ermi) python mi/train_functionlearning.py --env-type claude_dim1_maxsteps25 --num-episodes 100000 --max-steps 25 --ess 0 --offset 0 --scale 0 --job-array --ess-init 0.0 --optimizer adam --num-dims 1 --sample-to-match-max-steps --loss nll --env-name claude_generated_functionlearningtasks_paramsNA_dim1_data20_tasks9991_run0_procid0_pversion2 --env-dir /u/ajagadish/ermi/functionlearning/data/generated_tasks --save-dir /u/ajagadish/ermi/functionlearning/trained_models/ --save-every 100 --print-every 10  --first-run-id 0 --noise 0.0 --model-name transformer --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle 
# (sf ermi) python mi/train_functionlearning.py --env-type claude_dim1_maxsteps25 --num-episodes 100000 --max-steps 25 --ess 0 --offset 0 --scale 0 --job-array --ess-init 0.0 --optimizer schedulefree --num-dims 1 --sample-to-match-max-steps --loss nll --env-name claude_generated_functionlearningtasks_paramsNA_dim1_data20_tasks9991_run0_procid0_pversion2 --env-dir /u/ajagadish/ermi/functionlearning/data/generated_tasks --save-dir /u/ajagadish/ermi/functionlearning/trained_models/ --save-every 100 --print-every 10  --first-run-id 0 --noise 0.0 --model-name transformer --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle 
# (does not finish training) python mi/train_functionlearning.py --env-type claude_dim1_maxsteps25  --num-episodes 500000 --ess ${SLURM_ARRAY_TASK_ID} --optimizer schedulefree --offset 0 --scale 0.25 --job-array --ess-init 0.0 --annealing-fraction 0.167 --max-steps 25 --num-dims 1 --sample-to-match-max-steps --loss nll --env-name claude_generated_functionlearningtasks_paramsNA_dim1_data20_tasks9991_run0_procid0_pversion2 --env-dir /u/ajagadish/ermi/functionlearning/data/generated_tasks --save-dir /u/ajagadish/ermi/functionlearning/trained_models/ --save-every 100 --print-every 10  --first-run-id 0 --noise 0.0 --model-name transformer --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle  
# (adam, leads to nans) python mi/train_functionlearning.py --env-type claude_dim1_maxsteps25  --num-episodes 250000 --ess ${SLURM_ARRAY_TASK_ID} --optimizer adam --offset 0 --scale 0.5 --job-array --ess-init 0.0 --annealing-fraction 0.167 --max-steps 25 --num-dims 1 --sample-to-match-max-steps --loss nll --env-name claude_generated_functionlearningtasks_paramsNA_dim1_data20_tasks9991_run0_procid0_pversion2 --env-dir /u/ajagadish/ermi/functionlearning/data/generated_tasks --save-dir /u/ajagadish/ermi/functionlearning/trained_models/ --save-every 100 --print-every 10  --first-run-id 0 --noise 0.0 --model-name transformer --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle  
# python mi/train_functionlearning.py --env-type claude_dim1_maxsteps25  --num-episodes 250000 --ess ${SLURM_ARRAY_TASK_ID} --optimizer schedulefree --offset 0 --scale 0.5 --job-array --ess-init 0.0 --annealing-fraction 0.167 --max-steps 25 --num-dims 1 --sample-to-match-max-steps --loss nll --env-name claude_generated_functionlearningtasks_paramsNA_dim1_data20_tasks9991_run0_procid0_pversion2 --env-dir /u/ajagadish/ermi/functionlearning/data/generated_tasks --save-dir /u/ajagadish/ermi/functionlearning/trained_models/ --save-every 100 --print-every 10  --first-run-id 0 --noise 0.0 --model-name transformer --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle  
python mi/train_functionlearning.py --env-type claude_dim1_maxsteps25  --dynamic-scaling --num-episodes 250000 --ess ${SLURM_ARRAY_TASK_ID} --optimizer schedulefree --offset 0 --scale 0.5 --job-array --ess-init 0.0 --annealing-fraction 0.167 --max-steps 25 --num-dims 1 --sample-to-match-max-steps --loss nll --env-name claude_generated_functionlearningtasks_paramsNA_dim1_data20_tasks9991_run0_procid0_pversion2 --env-dir /u/ajagadish/ermi/functionlearning/data/generated_tasks --save-dir /u/ajagadish/ermi/functionlearning/trained_models/ --save-every 100 --print-every 10  --first-run-id 0 --noise 0.0 --model-name transformer --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle  

# MI
# python mi/train_functionlearning.py --synthetic --num-episodes 100000 --max-steps 25 --num-dims 1 --loss nll --env-name synthetic --save-dir /u/ajagadish/ermi/functionlearning/trained_models/ --save-every 100 --print-every 10  --first-run-id 0 --noise 0.01 --model-name transformer --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle 
# ERMI
# python mi/train_functionlearning.py --env-type claude_dim1_maxsteps25 --num-episodes 100000 --max-steps 25 --num-dims 1 --sample-to-match-max-steps --loss nll --env-name claude_generated_functionlearningtasks_paramsNA_dim1_data20_tasks9991_run0_procid0_pversion2 --env-dir /u/ajagadish/ermi/functionlearning/data/generated_tasks --save-dir /u/ajagadish/ermi/functionlearning/trained_models/ --save-every 100 --print-every 10  --first-run-id 0 --noise 0.0 --model-name transformer --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle 

# python mi/train_functionlearning.py --num-episodes 100000 --max-steps 25 --num-dims 1 --sample-to-match-max-steps --loss nll --env-name claude_generated_functionlearningtasks_paramsNA_dim1_data20_tasks9991_run0_procid0_pversion2 --env-dir /u/ajagadish/ermi/functionlearning/data/generated_tasks --save-dir /u/ajagadish/ermi/functionlearning/trained_models/ --save-every 100 --print-every 10  --first-run-id 0 --noise 0.0 --model-name transformer --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle 
# python mi/train_functionlearning.py --num-episodes 100000 --max-steps 20 --num-dims 1 --sample-to-match-max-steps --loss nll --env-name claude_generated_functionlearningtasks_paramsNA_dim1_data20_tasks9991_run0_procid0_pversion2 --env-dir /u/ajagadish/ermi/functionlearning/data/generated_tasks --save-dir /u/ajagadish/ermi/functionlearning/trained_models/ --save-every 100 --print-every 10  --first-run-id 0 --noise 0.0 --model-name transformer --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle
